from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

from case_enrichment import enrich_record_from_body, write_manual_review_files
from dedupe import write_json


ROOT = Path(__file__).resolve().parents[1]
EXTERNAL_OCR_DIR = ROOT / "external_ocr"
OUTPUT_JSON_DIR = ROOT / "output" / "json"
OUTPUT_TEXT_DIR = ROOT / "output" / "text"
PUBLIC_OCR_TEXT_DIR = ROOT / "public" / "data" / "ocr_texts"


SUPPORTED_SUFFIXES = {".md", ".markdown", ".txt"}


def normalize_key(value: str) -> str:
    return re.sub(r"[^a-z0-9\u4e00-\u9fff]+", "", value.lower())


def load_records() -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for path in sorted(OUTPUT_JSON_DIR.glob("case_*.json")):
        with path.open("r", encoding="utf-8") as f:
            records.append(json.load(f))
    return records


def build_record_lookup(records: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    lookup: dict[str, dict[str, Any]] = {}
    for record in records:
        keys = [
            record.get("id", ""),
            Path(record.get("pdf_path", "")).stem,
            Path(record.get("source_file", "")).stem,
            Path(record.get("file_name", "")).stem,
        ]
        for key in keys:
            normalized = normalize_key(str(key))
            if normalized:
                lookup.setdefault(normalized, record)
    return lookup


def iter_external_texts(input_dir: Path) -> list[Path]:
    if not input_dir.exists():
        return []
    return sorted(path for path in input_dir.rglob("*") if path.suffix.lower() in SUPPORTED_SUFFIXES)


def external_text_to_plain_text(path: Path) -> str:
    text = path.read_text(encoding="utf-8", errors="ignore")
    if path.suffix.lower() in {".md", ".markdown"}:
        text = re.sub(r"!\[[^\]]*]\([^)]*\)", " ", text)
        text = re.sub(r"\[([^\]]+)]\([^)]*\)", r"\1", text)
        text = re.sub(r"`{1,3}", " ", text)
        text = re.sub(r"^\s{0,3}#{1,6}\s*", "", text, flags=re.M)
    return re.sub(r"\n{3,}", "\n\n", text).strip()


def import_text(record: dict[str, Any], source_path: Path, text: str) -> None:
    case_id = record["id"]
    OUTPUT_TEXT_DIR.mkdir(parents=True, exist_ok=True)
    PUBLIC_OCR_TEXT_DIR.mkdir(parents=True, exist_ok=True)
    output_text_path = OUTPUT_TEXT_DIR / f"{case_id}.txt"
    public_text_path = PUBLIC_OCR_TEXT_DIR / f"{case_id}.txt"
    output_text_path.write_text(text, encoding="utf-8")
    public_text_path.write_text(text, encoding="utf-8")

    record["ocr_status"] = "external_imported"
    record["extracted_text_status"] = "external_ocr"
    record["ocr_text_path"] = public_text_path.relative_to(ROOT / "public").as_posix()
    record["external_ocr_source"] = str(source_path)
    record["needs_ocr"] = False
    record["needs_manual_summary"] = False
    enrich_record_from_body(record, text)
    write_json(OUTPUT_JSON_DIR / f"{case_id}.json", record)


def main() -> int:
    parser = argparse.ArgumentParser(description="Import OCR text or Markdown generated by external tools such as MinerU.")
    parser.add_argument("--input-dir", default=str(EXTERNAL_OCR_DIR), help="Folder containing .md/.txt OCR outputs.")
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    records = load_records()
    lookup = build_record_lookup(records)
    imported = 0
    unmatched: list[str] = []

    for path in iter_external_texts(input_dir):
        record = lookup.get(normalize_key(path.stem))
        if not record:
            unmatched.append(str(path))
            continue
        text = external_text_to_plain_text(path)
        if not text:
            unmatched.append(str(path))
            continue
        import_text(record, path, text)
        imported += 1
        print(f"imported {record['id']} <- {path.name}")

    refreshed_records = load_records()
    write_manual_review_files(refreshed_records)
    print(f"Imported: {imported}")
    print(f"Unmatched: {len(unmatched)}")
    if unmatched:
        print("Unmatched files:")
        for item in unmatched[:30]:
            print(f"  {item}")
        if len(unmatched) > 30:
            print(f"  ... and {len(unmatched) - 30} more")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
